In [1]:
import numpy as np

### Preprocessing

In [1]:
import preprocess

In [2]:
preprocess.preprocess()

***1. Load reviews from file...
	total reviews: 5212
***2. Parse reviews into sentences...
	total processed reviews: 5212
	total scentences: 36816
***3. Create vocabulary...
	total terms: 3656


In [3]:
from aspect_segmentation import Data

In [4]:
import LRR, pickle

In [5]:
data = pickle.load(open("data_dump.pickle", "rb"))

In [6]:
data

In [7]:
data.aspect_sent

array([ 1335., 12363., 14077., 12347.,  3357.,  2639.,  1027.])

In [8]:
len(data.aspect_words[0])

3656

In [9]:
data.aspect_terms

[['valu', 'price', 'qualiti', 'worth'],
 ['room', 'suit', 'view', 'bed', 'hotel'],
 ['locat', 'traffic', 'minut', 'restaur', 'hotel', 'room'],
 ['clean', 'dirti', 'maintain', 'smell', 'room', 'bathroom', 'hotel'],
 ['stuff', 'check', 'help', 'reserv', 'staff'],
 ['servic', 'food', 'breakfast', 'buffet'],
 ['busi', 'center', 'comput', 'internet']]

In [10]:
print(data.vocab_dict)

{'bad': 0, 'servic': 1, 'price': 2, 'stay': 3, 'westin': 4, 'waterfront': 5, '5': 6, 'night': 7, 'confer': 8, 'charg': 9, 'internet': 10, 'food': 11, 'fairli': 12, 'steep': 13, 'see': 14, 'expect': 15, 'rude': 16, 'behavior': 17, 'staff': 18, 'perhap': 19, '20': 20, 'someth': 21, 'command': 22, 'type': 23, 'respect': 24, 'usual': 25, 'busi': 26, 'class': 27, 'wow': 28, 'room': 29, 'mate': 30, 'arriv': 31, 'boston': 32, 'yet': 33, 'allow': 34, 'add': 35, 'name': 36, 'check': 37, 'could': 38, 'access': 39, 'serious': 40, 'given': 41, 'singl': 42, 'king': 43, 'bed': 44, 'told': 45, 'reserv': 46, '2': 47, '1': 48, 'respons': 49, 'pull': 50, 'print': 51, 'comput': 52, 'handicap': 53, 'two': 54, 'fine': 55, 'also': 56, 'guest': 57, 'suit': 58, 'near': 59, 'convent': 60, 'center': 61, 'would': 62, 'highli': 63, 'recommend': 64, 'larger': 65, 'nicer': 66, 'great': 67, 'much': 68, 'cheaper': 69, 'exampl': 70, 'omelet': 71, '16': 72, 'tea': 73, '6': 74, 'day': 75, '12': 76, 'oh': 77, 'yeah': 78,

In [11]:
lrr = LRR.LRR(7, 3656, data)

In [12]:
%time W = lrr.calculateW()

CPU times: user 1.2 s, sys: 99.6 ms, total: 1.3 s
Wall time: 1.3 s


In [13]:
W[0]

array([[1., 1., 4., ..., 0., 0., 0.],
       [0., 0., 2., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [14]:
lrr.Beta

array([[0.17833223, 0.16645818, 0.95392187, ..., 0.28508828, 0.40535325,
        0.59849487],
       [0.70163919, 0.49549732, 0.83629643, ..., 0.85675104, 0.78805532,
        0.87813811],
       [0.7626169 , 0.74774694, 0.88877885, ..., 0.53534912, 0.42588578,
        0.84066302],
       ...,
       [0.56820758, 0.49105835, 0.15165884, ..., 0.64797376, 0.6098656 ,
        0.72838842],
       [0.95294298, 0.19034349, 0.79077091, ..., 0.93867515, 0.96858588,
        0.73155228],
       [0.02393075, 0.40868457, 0.83850501, ..., 0.39986046, 0.13591262,
        0.39457   ]])

In [15]:
d=0
for i in range(7):
    print("s%d=" % i, np.dot(lrr.Beta[i], W[d][i]))

NameError: name 'np' is not defined

In [16]:
lrr.Mu

array([0.52763284, 0.96028044, 0.42684144, 0.17516309, 0.11634243,
       0.88562235, 0.3393908 ])

In [17]:
W[0].shape

(7, 3656)

In [18]:
np.linalg.inv(lrr.Omega)

array([[ 0.34186588, -1.08209449, -1.7204864 ,  2.09133048, -2.15856499,
         2.41880371,  1.58830941],
       [ 1.47237396, -0.94712478,  0.15231031, -0.85270708,  0.24321765,
         0.44603781, -0.5665486 ],
       [-0.25280831,  0.80585691, -0.2256783 ,  0.91267985,  0.43933968,
        -1.35080251,  0.49135203],
       [-0.58324988, -0.167212  ,  1.19863663,  0.14922917,  0.55628885,
        -0.55806545, -0.49597692],
       [-0.97676363,  1.59228861,  1.70795192, -1.19545598,  0.78891508,
        -1.91328538, -0.35035909],
       [-0.76951307, -0.23168571, -0.61191005, -0.376778  ,  0.0527722 ,
         0.79187908,  1.20694945],
       [ 0.55893945,  0.3353512 , -0.5766575 , -0.11833026,  0.26902545,
         0.62878742, -0.9933589 ]])

In [19]:
lambda s: s

<function __main__.<lambda>(s)>

In [20]:
a = np.zeros(7)

In [21]:
a

array([0., 0., 0., 0., 0., 0., 0.])

In [22]:
a += 1/7

In [23]:
a

array([0.14285714, 0.14285714, 0.14285714, 0.14285714, 0.14285714,
       0.14285714, 0.14285714])